Coins/markets function
Niraj-Kamdar/defiwrapper pull request #73
Opened 2021-11-19 17:46 UTC by WHYTEWYLL

Fixes #21

2021-11-21 07:50 UTC, Niraj-Kamdar requested changes

2021-11-21 07:50 UTC, Niraj-Kamdar commented on .vscode/extensions.json
> +{
Can you add this in .gitignore

2021-11-21 20:45 UTC, WHYTEWYLL commented on .vscode/extensions.json
> +{
Doneª

2021-11-22 07:33 UTC, Niraj-Kamdar requested changes
It has to be named `schema.graphql` and `e2e.json`

2021-11-22 07:33 UTC, Niraj-Kamdar commented on packages/coingecko/recipes/endpoints/coinsMarket/coinsMarket.graphql
> +query coinsMarkets (
rename this to `schema.graphql`

2021-11-22 09:16 UTC, WHYTEWYLL commented on packages/coingecko/recipes/endpoints/coinsMarket/coinsMarket.graphql
> +query coinsMarkets (
Done, and pushed!

2021-11-22 09:52 UTC, Niraj-Kamdar commented on packages/coingecko/src/query/schema.graphql
> +    simplePrice(
format this. feel free to look into auto formatters for graphql if you are interested

2021-11-23 13:20 UTC, merged