feat(coingecko): add endpoint for token market chart
Niraj-Kamdar/defiwrapper pull request #92
Opened 2021-12-01 20:24 UTC by codeproline

Hey there,

This PR adds endpoint for token market chart at `/coins/{id}/contract/{contract_address}/market_chart`.

Closes #25

2021-12-02 11:16 UTC, Niraj-Kamdar requested changes
Please add integration tests also so CI can verify it. Going forward we want to improve our test coverage and have atleast one e2e test for any new function.

2021-12-02 11:16 UTC, Niraj-Kamdar commented on packages/coingecko/src/query/routes/tokenInfo.ts
> +    market_cap_change_24h: getStringProperty(json, "market_cap_change_24h"),
nice catch!

2021-12-02 11:16 UTC, Niraj-Kamdar commented on packages/coingecko/src/query/routes/tokenMarketChart.ts
> +    throw Error(response.statusText);
```suggest
    throw new Error(response.statusText);
```

2021-12-02 12:11 UTC, codeproline commented on packages/coingecko/src/query/routes/tokenInfo.ts
> +    market_cap_change_24h: getStringProperty(json, "market_cap_change_24h"),
Thanks for pointing this out👍🏻

2021-12-02 12:12 UTC, codeproline commented on packages/coingecko/src/query/routes/tokenMarketChart.ts
> +    throw Error(response.statusText);
Thanks for pointing this out👍🏻

2021-12-02 14:09 UTC, codeproline commented
Hey @Niraj-Kamdar, I have added new integration test for this function.

2021-12-02 15:35 UTC, Niraj-Kamdar approved these changes
LGTM!

2021-12-02 15:36 UTC, merged

2021-12-03 14:53 UTC, rihp commented
500$ as reward has been paid out to @codeproline  👏 
txn : https://polygonscan.com/tx/0x4602d767ea5d1b585009685e588d11a137324e1e0c66725e1ad7b35a6d4bdb40